### ISSUE TITLE
Streamlit app not starting

### ISSUE THREAD

**Issue by caronjerome** [Snowflake-Labs/snowflake-demo-streamlit#14]
When creating a SiS app with default settings on 09/25/24, App does not start with following message : 

An error has occurred
Error running Streamlit: [391546] SQL compilation error: Cannot create a Python function with the specified packages. Please check your packages specification and try again. 'One or more package conflicts were detected.'. Hint: These packages are available in other python runtimes:["snowflake-snowpark-python"->[3.9, 3.10, 3.11], "sqlparse==0.4.4"->[3.9, 3.10, 3.11], "pandas==2.0.3"->[3.9, 3.10, 3.11], "altair==5.0.1"->[3.9, 3.10, 3.11]].

**Comment by sfc-gh-asaini** [comment]
Hey @caronjerome: This error is due to a dependency mismatch related to Python >= 3.9. 

Streamlit in Snowflake currently supports Python 3.8, however, Snowflake is rolling out support Python 3.9, 3.10 and 3.11 as an opt in feature starting mid October. Recommend trying this again once your ACCOUNTADMIN has opted in to using a higher Python version as part of the next Behavior Change Bundle. This will be updated on this page around mid October: https://docs.snowflake.com/en/release-notes/behavior-changes
